# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#############
#   Notes   #
#############

# This config assumes you have a Nerd Font installed and enabled in your terminal.
# I use 'FiraCode Nerd Font Mono', but you should be able to use any Nerd Font you like.

################
#   Settings   #
################

# Inserts a blank line between shell prompts
add_newline = true

# Maximum time it may take to produce the prompt
command_timeout = 3000

########################
#   Webber's colours   #
########################

# Bright pink: (bg:#bfc2ff fg:#272b60)
# Middle pink, bright text: (bg:#3e4278 fg:#e0e0ff)
# Middle pink, faded text: (bg:#3e4278 fg:#e0e0ff)
# Dark pink, regular text: (bg:#444559 fg:#e1e0f9)
# Dark pink, highlighted: (bg:#444559 fg:#bfc2ff)


###############
#   Prompts   #
###############

# Right prompt. This is displayed on the right side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
#
# Note: Not supported in Powershell
# @see: https://starship.rs/advanced-config/#enable-right-prompt
right_format = """
[î‚¶](bg:transparent fg:#3e4278)\
$time\
$memory_usage\
[î‚´](fg:#3e4278 bg:transparent)\
\
"""

# Left prompt. This is displayed on the left side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
format = """
[î‚¶](bg:#transparent fg:#bfc2ff)\
$os\
$username\
[î‚´](fg:#bfc2ff bg:#3e4278)\
$directory\
${custom.pregit}\
$git_branch\
$git_state\
$git_metrics\
$git_status\
${custom.postgit}\
${custom.nogit}\
$package\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$nim\
$rust\
$scala\
$docker_context\
$character\
"""

########################
#   Special sections   #
########################

# Exit code indicator
[character] # The name of the module we are configuring is 'character'
success_symbol = '[î‚¶](bg:#3e4278 fg:#bfc2ff)[ó±‡«](bg:#bfc2ff fg:#272b60)[î‚´](fg:#bfc2ff bg:transparent)'
error_symbol = '[î‚¶](bg:#3e4278 fg:#ffb4ab)[ó±‡«](bg:#ffb4ab fg:#690005)[î‚´](fg:#ffb4ab bg:transparent)'
format = '$symbol '

# cross-platform way to check if we are in a git repo, takes 200ms
[custom.nogit]
when = ''' git rev-parse --git-dir ; test $? = False '''
format = '[ ](bg:#3e4278)'
disabled = true

# Either `Administrator`, `root` or the current user's username.
[username]
show_always = true
style_user = "bg:#bfc2ff fg:#272b60"
style_root = "bg:#bfc2ff fg:#272b60"
format = '[ $user]($style)'
disabled = false

# Displays a symbol that represents the current operating system
[os]
style = "bg:#bfc2ff fg:#272b60"
format = '[$symbol]($style)'
disabled = false # This doesn't work in pwsh in Webstorm terminal.

# The current directory
[directory]
style = "bg:#3e4278 fg:#e0e0ff"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "â€¦/"

[hostname]
ssh_symbol = "î¬"

[memory_usage]
symbol = "ó°›"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#3e4278"
format = '[$time]($style)'

#######################
#   Version control   #
#######################


[git_branch]
symbol = "ï˜"
style = "bg:#444559 fg:#e1e0f9"
format = '[î‚´](fg:#3e4278 bg:#444559)[ $symbol](bg:#444559 fg:#bfc2ff)[ $branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bg:#444559 fg:bold red)'
rebase = '[î©¤ REBASING](bg:#444559 fg:bold green)'
merge = '[îœ§ MERGING](bg:#444559 fg:bold yellow)'
bisect = '[ğŸ” BISECTING](bg:#444559 fg:bold blue)'
am = '[AM](bg:#444559 fg:bold green)'
am_or_rebase = '[AM/REBASE](bg:#444559 fg:bold green)'
revert = '[ó°• REVERTING](bg:#444559 fg:bold red)'

[git_metrics]
added_style = "bg:#444559 fg:#e8b9d4"
deleted_style = "bg:#444559 fg:#ffb4ab"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[git_status]
style = "bg:#444559 fg:#bfc2ff"
conflicted = '=' # This branch has merge conflicts.
ahead = 'îª '
behind = 'îª'
diverged = 'ó±¡·'
up_to_date = ''
untracked = '?'
stashed = 'ï…•'
modified = 'ï‘„'
staged = 'î«´'
renamed = 'Â»'
deleted = 'âœ˜'
format = '([($all_status )($ahead_behind )]($style))[î‚¶](bg:#444559 fg:#3e4278)'

[fossil_branch]
symbol = "ï˜"

[hg_branch]
symbol = "ï˜"

[pijul_channel]
symbol = "ï˜"

############################
#   Contexts (canonical)   #
############################

[nodejs]
symbol = "îœ˜"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[bun]
symbol = "ó°…Ÿ"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ (context) ]($style)'

[package]
format = '($style)[> $symbol$version ]($style)'
symbol = 'ğŸ“¦ '
version_format = 'v${raw}'
style = 'bold 208 bg:#3e4278'
display_private = false
disabled = true
################
#   Contexts   #
################

[aws]
symbol = "îŒ½"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[c]
symbol = "î˜"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[conda]
symbol = "ï„Œ"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[dart]
symbol = "î˜"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[elixir]
symbol = "î˜­"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[elm]
symbol = "î˜¬"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[golang]
symbol = "î˜§"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[gradle]
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[haskell]
symbol = "î·"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[haxe]
symbol = "î™¦"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[java]
symbol = "î‰–"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[julia]
symbol = "î˜¤"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[lua]
symbol = "î˜ "
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[ocaml]
symbol = "î™º"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[perl]
symbol = "î™¾"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[python]
symbol = "îˆµ"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[rlang]
symbol = "ó°Ÿ”"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[ruby]
symbol = "î‘"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[scala]
symbol = "îœ·"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[swift]
symbol = "î•"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

[zig]
symbol = "îš©"
style = "bg:#3e4278 fg:#e0e0ff"
format = '[$symbol](bg:#3e4278 fg:#bfc2ff)[ ($version) ]($style)'

#############
#   Other   #
#############

[nix_shell]
symbol = "ïŒ“"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
